<?php if ($this->isPossibleOneStepCheckout()):?>
<div class="visible-md visible-lg">
    <button
        type="button"
        title="<?php echo $this->__('Checkout in One Step') ?>"
        class="button btn-proceed-checkout btn-checkout button-merah<?php
        if ($this->isDisabled()):
            ?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php
        endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
        <span><span><?php echo $this->__('Checkout in One Step') ?></span></span></button>
</div>

<?php endif?>
