<?php
/**
 * Magento
 *
 * @author    Faspay http://faspay.mediaindonusa.com <cs@mediaindonusa.com>
 * @copyright Copyright (C) 2013 MediaIndonusa. (http://faspay.mediaindonusa.com)
 *
**/
?>

<?php
$_code = $this->getMethodCode();

if($_code=="BCAKlikpay"){
	$lastOrderId	= Mage::getSingleton('checkout/session')->getLastRealOrderId();
	$session		= Mage::getSingleton('checkout/session');
	$order			= Mage::getModel('sales/order')->loadByIncrementId($lastOrderId);
	$items			= $session->getQuote()->getAllItems();
	
	$index = 0;
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<li>
		<form action="" >
			<table id="checkout-review-table" class="data-table">
				<thead>
					<th>Product Name</th>
					<th>Tipe Pembayaran</th>
				</thead>
				<tbody>
					<?php foreach ($items as $item) { ?>
					<?php
						$itemprice	= $item->getPrice();				
						$itemqty	= $item->getQty();
						$totprcitem	= $itemqty * $itemprice;
						 
					?>
					<tr>
						<td>
							<?php echo $item->getName(); ?>
						</td>
						<td>
							<select id="payment_tenor_<?php echo $index ?>" onChange="checkSelectInput()" class="payment_tenor required" type="payment_tenor" name="payment[payment_tenor_<?php echo $index; ?>]" >
								<option value="00">Pembayaran Full Payment</option>
								<?php if (Mage::getStoreConfig('payment/BCAKlikpay/installment_3_month')== 1 ){ ?>
									<?php if ($totprcitem >= Mage::getStoreConfig('payment/BCAKlikpay/min_price_3_month') and Mage::getStoreConfig('payment/BCAKlikpay/installment_3_month')== 1 ) {?>
										<option value="03">Pembayaran Periode 3 Bulan</option>
									<?php } ?>
								<?php } ?>
								<?php if (Mage::getStoreConfig('payment/BCAKlikpay/installment_6_month')== 1){ ?>
									<?php if ($totprcitem >= Mage::getStoreConfig('payment/BCAKlikpay/min_price_6_month') and Mage::getStoreConfig('payment/BCAKlikpay/installment_6_month')== 1 )  {?>
										<option value="06">Pembayaran Periode 6 Bulan</option>
									<?php } ?>
								<?php } ?>
								<?php if (Mage::getStoreConfig('payment/BCAKlikpay/installment_12_month')== 1){ ?>
									<?php if ($totprcitem >= Mage::getStoreConfig('payment/BCAKlikpay/min_price_12_month') and Mage::getStoreConfig('payment/BCAKlikpay/installment_12_month')== 1 )  {?>
										<option value="12">Pembayaran Periode 12 Bulan</option>
									<?php } ?>
								<?php } ?>
								<?php if (Mage::getStoreConfig('payment/BCAKlikpay/installment_24_month')== 1){ ?>
									<?php if ($totprcitem >= Mage::getStoreConfig('payment/BCAKlikpay/min_price_24_month')and Mage::getStoreConfig('payment/BCAKlikpay/installment_24_month')== 1 ) {?>
										<option value="24">Pembayaran Periode 24 Bulan</option>
									<?php } ?>
								<?php } ?>
							</select>
						</td>
					</tr>
					<?php 
						$index++;
						}
					?>
				</tbody>
			</table>
		</form>
	</li>
</ul>

<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
<?php } ?>