/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 5.5.36 : Database - bagus
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `bg_ks_directory_regency` */

insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (1,'ID001','ID001001','Kab. Aceh Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (2,'ID001','ID001002','Kab. Aceh Barat Daya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (3,'ID001','ID001003','Kab. Aceh Besar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (4,'ID001','ID001004','Kab. Aceh Jaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (5,'ID001','ID001005','Kab. Aceh Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (6,'ID001','ID001006','Kab. Aceh Singkil',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (7,'ID001','ID001007','Kab. Aceh Tamiang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (8,'ID001','ID001008','Kab. Aceh Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (9,'ID001','ID001009','Kab. Aceh Tenggara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (10,'ID001','ID001010','Kab. Aceh Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (11,'ID001','ID001011','Kab. Aceh Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (12,'ID001','ID001012','Kab. Bener Meriah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (13,'ID001','ID001013','Kab. Bireuen',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (14,'ID001','ID001014','Kab. Gayo Lues',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (15,'ID001','ID001015','Kab. Nagan Raya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (16,'ID001','ID001016','Kab. Pidie',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (17,'ID001','ID001017','Kab. Pidie Jaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (18,'ID001','ID001018','Kab. Simeulue',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (19,'ID001','ID001019','Kota Banda Aceh',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (20,'ID001','ID001020','Kota Langsa',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (21,'ID001','ID001021','Kota Lhokseumawe',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (22,'ID001','ID001022','Kota Sabang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (23,'ID001','ID001023','Kota Subulussalam',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (24,'ID002','ID002001','Kab. Badung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (25,'ID002','ID002002','Kab. Bangli',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (26,'ID002','ID002003','Kab. Buleleng',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (27,'ID002','ID002004','Kab. Gianyar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (28,'ID002','ID002005','Kab. Jembrana',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (29,'ID002','ID002006','Kab. Karangasem',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (30,'ID002','ID002007','Kab. Klungkung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (31,'ID002','ID002008','Kab. Tabanan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (32,'ID002','ID002009','Kota Denpasar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (33,'ID003','ID003001','Kab. Bangka',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (34,'ID003','ID003002','Kab. Bangka Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (35,'ID003','ID003003','Kab. Bangka Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (36,'ID003','ID003004','Kab. Bangka Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (37,'ID003','ID003005','Kab. Belitung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (38,'ID003','ID003006','Kab. Belitung Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (39,'ID003','ID003007','Kota Pangkal Pinang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (40,'ID004','ID004001','Kab. Lebak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (41,'ID004','ID004002','Kab. Pandeglang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (42,'ID004','ID004003','Kab. Serang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (43,'ID004','ID004004','Kab. Tangerang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (44,'ID004','ID004005','Kota Cilegon',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (45,'ID004','ID004006','Kota Serang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (46,'ID004','ID004007','Kota Tangerang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (47,'ID004','ID004008','Kota Tangerang Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (48,'ID005','ID005001','Kab. Bengkulu Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (49,'ID005','ID005002','Kab. Bengkulu Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (50,'ID005','ID005003','Kab. Bengkulu Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (51,'ID005','ID005004','Kab. Kaur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (52,'ID005','ID005005','Kab. Kepahiang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (53,'ID005','ID005006','Kab. Lebong',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (54,'ID005','ID005007','Kab. Muko Muko',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (55,'ID005','ID005008','Kab. Rejang Lebong',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (56,'ID005','ID005009','Kab. Seluma',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (57,'ID005','ID005010','Kota Bengkulu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (58,'ID006','ID006001','Kab. Bantul',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (59,'ID006','ID006002','Kab. Gunung Kidul',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (60,'ID006','ID006003','Kab. Kulon Progo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (61,'ID006','ID006004','Kab. Sleman',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (62,'ID006','ID006005','Kota Yogyakarta',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (63,'ID007','ID007001','Kab. Kepulauan Seribu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (64,'ID007','ID007002','Kota Jakarta Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (65,'ID007','ID007003','Kota Jakarta Pusat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (66,'ID007','ID007004','Kota Jakarta Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (67,'ID007','ID007005','Kota Jakarta Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (68,'ID007','ID007006','Kota Jakarta Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (69,'ID008','ID008001','Kab. Boalemo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (70,'ID008','ID008002','Kab. Bone Bolango',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (71,'ID008','ID008003','Kab. Gorontalo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (72,'ID008','ID008004','Kab. Gorontalo Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (73,'ID008','ID008005','Kab. Pohuwato',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (74,'ID008','ID008006','Kota Gorontalo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (75,'ID009','ID009001','Kab. Batang Hari',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (76,'ID009','ID009002','Kab. Bungo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (77,'ID009','ID009003','Kab. Kerinci',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (78,'ID009','ID009004','Kab. Merangin',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (79,'ID009','ID009005','Kab. Muaro Jambi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (80,'ID009','ID009006','Kab. Sarolangun',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (81,'ID009','ID009007','Kab. Tanjung Jabung Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (82,'ID009','ID009008','Kab. Tanjung Jabung Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (83,'ID009','ID009009','Kab. Tebo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (84,'ID009','ID009010','Kota Jambi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (85,'ID009','ID009011','Kota Sungaipenuh',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (86,'ID010','ID010001','Kab. Bandung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (87,'ID010','ID010002','Kab. Bandung Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (88,'ID010','ID010003','Kab. Bekasi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (89,'ID010','ID010004','Kab. Bogor',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (90,'ID010','ID010005','Kab. Ciamis',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (91,'ID010','ID010006','Kab. Cianjur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (92,'ID010','ID010007','Kab. Cirebon',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (93,'ID010','ID010008','Kab. Garut',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (94,'ID010','ID010009','Kab. Indramayu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (95,'ID010','ID010010','Kab. Karawang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (96,'ID010','ID010011','Kab. Kuningan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (97,'ID010','ID010012','Kab. Majalengka',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (98,'ID010','ID010013','Kab. Pangandaran',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (99,'ID010','ID010014','Kab. Purwakarta',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (100,'ID010','ID010015','Kab. Subang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (101,'ID010','ID010016','Kab. Sukabumi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (102,'ID010','ID010017','Kab. Sumedang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (103,'ID010','ID010018','Kab. Tasikmalaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (104,'ID010','ID010019','Kota Bandung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (105,'ID010','ID010020','Kota Banjar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (106,'ID010','ID010021','Kota Bekasi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (107,'ID010','ID010022','Kota Bogor',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (108,'ID010','ID010023','Kota Cimahi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (109,'ID010','ID010024','Kota Cirebon',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (110,'ID010','ID010025','Kota Depok',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (111,'ID010','ID010026','Kota Sukabumi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (112,'ID010','ID010027','Kota Tasikmalaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (113,'ID011','ID011001','Kab. Banjarnegara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (114,'ID011','ID011002','Kab. Banyumas',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (115,'ID011','ID011003','Kab. Batang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (116,'ID011','ID011004','Kab. Blora',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (117,'ID011','ID011005','Kab. Boyolali',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (118,'ID011','ID011006','Kab. Brebes',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (119,'ID011','ID011007','Kab. Cilacap',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (120,'ID011','ID011008','Kab. Demak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (121,'ID011','ID011009','Kab. Grobogan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (122,'ID011','ID011010','Kab. Jepara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (123,'ID011','ID011011','Kab. Karanganyar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (124,'ID011','ID011012','Kab. Kebumen',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (125,'ID011','ID011013','Kab. Kendal',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (126,'ID011','ID011014','Kab. Klaten',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (127,'ID011','ID011015','Kab. Kudus',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (128,'ID011','ID011016','Kab. Magelang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (129,'ID011','ID011017','Kab. Pati',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (130,'ID011','ID011018','Kab. Pekalongan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (131,'ID011','ID011019','Kab. Pemalang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (132,'ID011','ID011020','Kab. Purbalingga',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (133,'ID011','ID011021','Kab. Purworejo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (134,'ID011','ID011022','Kab. Rembang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (135,'ID011','ID011023','Kab. Semarang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (136,'ID011','ID011024','Kab. Sragen',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (137,'ID011','ID011025','Kab. Sukoharjo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (138,'ID011','ID011026','Kab. Tegal',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (139,'ID011','ID011027','Kab. Temanggung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (140,'ID011','ID011028','Kab. Wonogiri',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (141,'ID011','ID011029','Kab. Wonosobo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (142,'ID011','ID011030','Kota Magelang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (143,'ID011','ID011031','Kota Pekalongan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (144,'ID011','ID011032','Kota Salatiga',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (145,'ID011','ID011033','Kota Semarang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (146,'ID011','ID011034','Kota Surakarta',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (147,'ID011','ID011035','Kota Tegal',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (148,'ID012','ID012001','Kab. Bangkalan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (149,'ID012','ID012002','Kab. Banyuwangi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (150,'ID012','ID012003','Kab. Blitar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (151,'ID012','ID012004','Kab. Bojonegoro',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (152,'ID012','ID012005','Kab. Bondowoso',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (153,'ID012','ID012006','Kab. Gresik',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (154,'ID012','ID012007','Kab. Jember',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (155,'ID012','ID012008','Kab. Jombang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (156,'ID012','ID012009','Kab. Kediri',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (157,'ID012','ID012010','Kab. Lamongan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (158,'ID012','ID012011','Kab. Lumajang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (159,'ID012','ID012012','Kab. Madiun',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (160,'ID012','ID012013','Kab. Magetan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (161,'ID012','ID012014','Kab. Malang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (162,'ID012','ID012015','Kab. Mojokerto',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (163,'ID012','ID012016','Kab. Nganjuk',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (164,'ID012','ID012017','Kab. Ngawi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (165,'ID012','ID012018','Kab. Pacitan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (166,'ID012','ID012019','Kab. Pamekasan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (167,'ID012','ID012020','Kab. Pasuruan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (168,'ID012','ID012021','Kab. Ponorogo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (169,'ID012','ID012022','Kab. Probolinggo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (170,'ID012','ID012023','Kab. Sampang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (171,'ID012','ID012024','Kab. Sidoarjo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (172,'ID012','ID012025','Kab. Situbondo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (173,'ID012','ID012026','Kab. Sumenep',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (174,'ID012','ID012027','Kab. Trenggalek',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (175,'ID012','ID012028','Kab. Tuban',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (176,'ID012','ID012029','Kab. Tulungagung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (177,'ID012','ID012030','Kota Batu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (178,'ID012','ID012031','Kota Blitar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (179,'ID012','ID012032','Kota Kediri',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (180,'ID012','ID012033','Kota Madiun',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (181,'ID012','ID012034','Kota Malang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (182,'ID012','ID012035','Kota Mojokerto',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (183,'ID012','ID012036','Kota Pasuruan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (184,'ID012','ID012037','Kota Probolinggo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (185,'ID012','ID012038','Kota Surabaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (186,'ID013','ID013001','Kab. Bengkayang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (187,'ID013','ID013002','Kab. Kapuas Hulu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (188,'ID013','ID013003','Kab. Kayong Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (189,'ID013','ID013004','Kab. Ketapang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (190,'ID013','ID013005','Kab. Kubu Raya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (191,'ID013','ID013006','Kab. Landak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (192,'ID013','ID013007','Kab. Melawi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (193,'ID013','ID013008','Kab. Pontianak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (194,'ID013','ID013009','Kab. Sambas',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (195,'ID013','ID013010','Kab. Sanggau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (196,'ID013','ID013011','Kab. Sekadau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (197,'ID013','ID013012','Kab. Sintang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (198,'ID013','ID013013','Kota Pontianak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (199,'ID013','ID013014','Kota Singkawang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (200,'ID014','ID014001','Kab. Balangan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (201,'ID014','ID014002','Kab. Banjar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (202,'ID014','ID014003','Kab. Barito Kuala',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (203,'ID014','ID014004','Kab. Hulu Sungai Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (204,'ID014','ID014005','Kab. Hulu Sungai Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (205,'ID014','ID014006','Kab. Hulu Sungai Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (206,'ID014','ID014007','Kab. Kotabaru',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (207,'ID014','ID014008','Kab. Tabalong',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (208,'ID014','ID014009','Kab. Tanah Bumbu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (209,'ID014','ID014010','Kab. Tanah Laut',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (210,'ID014','ID014011','Kab. Tapin',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (211,'ID014','ID014012','Kota Banjarbaru',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (212,'ID014','ID014013','Kota Banjarmasin',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (213,'ID015','ID015001','Kab. Barito Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (214,'ID015','ID015002','Kab. Barito Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (215,'ID015','ID015003','Kab. Barito Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (216,'ID015','ID015004','Kab. Gunung Mas',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (217,'ID015','ID015005','Kab. Kapuas',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (218,'ID015','ID015006','Kab. Katingan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (219,'ID015','ID015007','Kab. Kotawaringin Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (220,'ID015','ID015008','Kab. Kotawaringin Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (221,'ID015','ID015009','Kab. Lamandau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (222,'ID015','ID015010','Kab. Murung Raya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (223,'ID015','ID015011','Kab. Pulang Pisau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (224,'ID015','ID015012','Kab. Seruyan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (225,'ID015','ID015013','Kab. Sukamara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (226,'ID015','ID015014','Kota Palangka Raya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (227,'ID016','ID016001','Kab. Berau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (228,'ID016','ID016002','Kab. Kutai Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (229,'ID016','ID016003','Kab. Kutai Kartanegara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (230,'ID016','ID016004','Kab. Kutai Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (231,'ID016','ID016005','Kab. Paser',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (232,'ID016','ID016006','Kab. Penajam Paser Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (233,'ID016','ID016007','Kota Balikpapan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (234,'ID016','ID016008','Kota Bontang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (235,'ID016','ID016009','Kota Samarinda',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (236,'ID017','ID017001','Kab. Bulungan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (237,'ID017','ID017002','Kab. Malinau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (238,'ID017','ID017003','Kab. Nunukan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (239,'ID017','ID017004','Kab. Tana Tidung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (240,'ID017','ID017005','Kota Tarakan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (241,'ID018','ID018001','Kab. Bintan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (242,'ID018','ID018002','Kab. Karimun',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (243,'ID018','ID018003','Kab. Kepulauan Anambas',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (244,'ID018','ID018004','Kab. Lingga',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (245,'ID018','ID018005','Kab. Natuna',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (246,'ID018','ID018006','Kota Batam',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (247,'ID018','ID018007','Kota Tanjung Pinang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (248,'ID019','ID019001','Kab. Lampung Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (249,'ID019','ID019002','Kab. Lampung Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (250,'ID019','ID019003','Kab. Lampung Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (251,'ID019','ID019004','Kab. Lampung Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (252,'ID019','ID019005','Kab. Lampung Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (253,'ID019','ID019006','Kab. Mesuji',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (254,'ID019','ID019007','Kab. Pesawaran',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (255,'ID019','ID019008','Kab. Pesisir Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (256,'ID019','ID019009','Kab. Pringsewu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (257,'ID019','ID019010','Kab. Tanggamus',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (258,'ID019','ID019011','Kab. Tulang Bawang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (259,'ID019','ID019012','Kab. Tulang Bawang Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (260,'ID019','ID019013','Kab. Way Kanan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (261,'ID019','ID019014','Kota Bandar Lampung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (262,'ID019','ID019015','Kota Metro',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (263,'ID020','ID020001','Kab. Buru',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (264,'ID020','ID020002','Kab. Buru Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (265,'ID020','ID020003','Kab. Kepulauan Aru',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (266,'ID020','ID020004','Kab. Maluku Barat Daya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (267,'ID020','ID020005','Kab. Maluku Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (268,'ID020','ID020006','Kab. Maluku Tenggara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (269,'ID020','ID020007','Kab. Maluku Tenggara Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (270,'ID020','ID020008','Kab. Seram Bagian Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (271,'ID020','ID020009','Kab. Seram Bagian Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (272,'ID020','ID020010','Kota Ambon',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (273,'ID020','ID020011','Kota Tual',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (274,'ID021','ID021001','Kab. Halmahera Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (275,'ID021','ID021002','Kab. Halmahera Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (276,'ID021','ID021003','Kab. Halmahera Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (277,'ID021','ID021004','Kab. Halmahera Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (278,'ID021','ID021005','Kab. Halmahera Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (279,'ID021','ID021006','Kab. Kepulauan Sula',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (280,'ID021','ID021007','Kab. Pulau Morotai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (281,'ID021','ID021008','Kota Ternate',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (282,'ID021','ID021009','Kota Tidore Kepulauan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (283,'ID022','ID022001','Kab. Bima',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (284,'ID022','ID022002','Kab. Dompu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (285,'ID022','ID022003','Kab. Lombok Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (286,'ID022','ID022004','Kab. Lombok Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (287,'ID022','ID022005','Kab. Lombok Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (288,'ID022','ID022006','Kab. Lombok Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (289,'ID022','ID022007','Kab. Sumbawa',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (290,'ID022','ID022008','Kab. Sumbawa Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (291,'ID022','ID022009','Kota Bima',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (292,'ID022','ID022010','Kota Mataram',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (293,'ID023','ID023001','Kab. Alor',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (294,'ID023','ID023002','Kab. Belu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (295,'ID023','ID023003','Kab. Ende',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (296,'ID023','ID023004','Kab. Flores Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (297,'ID023','ID023005','Kab. Kupang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (298,'ID023','ID023006','Kab. Lembata',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (299,'ID023','ID023007','Kab. Manggarai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (300,'ID023','ID023008','Kab. Manggarai Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (301,'ID023','ID023009','Kab. Manggarai Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (302,'ID023','ID023010','Kab. Nagekeo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (303,'ID023','ID023011','Kab. Ngada',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (304,'ID023','ID023012','Kab. Rote Ndao',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (305,'ID023','ID023013','Kab. Sabu Raijua',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (306,'ID023','ID023014','Kab. Sikka',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (307,'ID023','ID023015','Kab. Sumba Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (308,'ID023','ID023016','Kab. Sumba Barat Daya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (309,'ID023','ID023017','Kab. Sumba Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (310,'ID023','ID023018','Kab. Sumba Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (311,'ID023','ID023019','Kab. Timor Tengah Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (312,'ID023','ID023020','Kab. Timor Tengah Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (313,'ID023','ID023021','Kota Kupang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (314,'ID024','ID024001','Kab. Asmat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (315,'ID024','ID024002','Kab. Biak Numfor',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (316,'ID024','ID024003','Kab. Boven Digoel',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (317,'ID024','ID024004','Kab. Deiyai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (318,'ID024','ID024005','Kab. Dogiyai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (319,'ID024','ID024006','Kab. Intan Jaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (320,'ID024','ID024007','Kab. Jayapura',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (321,'ID024','ID024008','Kab. Jayawijaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (322,'ID024','ID024009','Kab. Keerom',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (323,'ID024','ID024010','Kab. Kepulauan Yapen',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (324,'ID024','ID024011','Kab. Lanny Jaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (325,'ID024','ID024012','Kab. Mamberamo Raya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (326,'ID024','ID024013','Kab. Mamberamo Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (327,'ID024','ID024014','Kab. Mappi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (328,'ID024','ID024015','Kab. Merauke',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (329,'ID024','ID024016','Kab. Mimika',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (330,'ID024','ID024017','Kab. Nabire',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (331,'ID024','ID024018','Kab. Nduga',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (332,'ID024','ID024019','Kab. Paniai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (333,'ID024','ID024020','Kab. Pegunungan Bintang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (334,'ID024','ID024021','Kab. Puncak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (335,'ID024','ID024022','Kab. Puncak Jaya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (336,'ID024','ID024023','Kab. Sarmi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (337,'ID024','ID024024','Kab. Supiori',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (338,'ID024','ID024025','Kab. Tolikara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (339,'ID024','ID024026','Kab. Waropen',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (340,'ID024','ID024027','Kab. Yahukimo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (341,'ID024','ID024028','Kab. Yalimo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (342,'ID024','ID024029','Kota Jayapura',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (343,'ID025','ID025001','Kab. Fakfak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (344,'ID025','ID025002','Kab. Kaimana',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (345,'ID025','ID025003','Kab. Manokwari',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (346,'ID025','ID025004','Kab. Manokwari Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (347,'ID025','ID025005','Kab. Maybrat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (348,'ID025','ID025006','Kab. Pegunungan Arfak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (349,'ID025','ID025007','Kab. Raja Ampat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (350,'ID025','ID025008','Kab. Sorong',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (351,'ID025','ID025009','Kab. Sorong Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (352,'ID025','ID025010','Kab. Tambrauw',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (353,'ID025','ID025011','Kab. Teluk Bintuni',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (354,'ID025','ID025012','Kab. Teluk Wondama',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (355,'ID025','ID025013','Kota Sorong',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (356,'ID026','ID026001','Kab. Bengkalis',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (357,'ID026','ID026002','Kab. Indragiri Hilir',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (358,'ID026','ID026003','Kab. Indragiri Hulu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (359,'ID026','ID026004','Kab. Kampar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (360,'ID026','ID026005','Kab. Kepulauan Meranti',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (361,'ID026','ID026006','Kab. Kuantan Singingi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (362,'ID026','ID026007','Kab. Pelalawan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (363,'ID026','ID026008','Kab. Rokan Hilir',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (364,'ID026','ID026009','Kab. Rokan Hulu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (365,'ID026','ID026010','Kab. Siak',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (366,'ID026','ID026011','Kota Dumai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (367,'ID026','ID026012','Kota Pekanbaru',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (368,'ID027','ID027001','Kab. Majene',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (369,'ID027','ID027002','Kab. Mamasa',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (370,'ID027','ID027003','Kab. Mamuju',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (371,'ID027','ID027004','Kab. Mamuju Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (372,'ID027','ID027005','Kab. Polewali Mandar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (373,'ID028','ID028001','Kab. Bantaeng',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (374,'ID028','ID028002','Kab. Barru',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (375,'ID028','ID028003','Kab. Bone',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (376,'ID028','ID028004','Kab. Bulukumba',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (377,'ID028','ID028005','Kab. Enrekang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (378,'ID028','ID028006','Kab. Gowa',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (379,'ID028','ID028007','Kab. Jeneponto',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (380,'ID028','ID028008','Kab. Luwu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (381,'ID028','ID028009','Kab. Luwu Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (382,'ID028','ID028010','Kab. Luwu Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (383,'ID028','ID028011','Kab. Maros',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (384,'ID028','ID028012','Kab. Pangkajene Kepulauan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (385,'ID028','ID028013','Kab. Pinrang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (386,'ID028','ID028014','Kab. Selayar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (387,'ID028','ID028015','Kab. Sidenreng Rappang/Rapang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (388,'ID028','ID028016','Kab. Sinjai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (389,'ID028','ID028017','Kab. Soppeng',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (390,'ID028','ID028018','Kab. Takalar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (391,'ID028','ID028019','Kab. Tana Toraja',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (392,'ID028','ID028020','Kab. Toraja Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (393,'ID028','ID028021','Kab. Wajo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (394,'ID028','ID028022','Kota Makassar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (395,'ID028','ID028023','Kota Palopo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (396,'ID028','ID028024','Kota Parepare',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (397,'ID029','ID029001','Kab. Banggai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (398,'ID029','ID029002','Kab. Banggai Kepulauan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (399,'ID029','ID029003','Kab. Buol',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (400,'ID029','ID029004','Kab. Donggala',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (401,'ID029','ID029005','Kab. Morowali',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (402,'ID029','ID029006','Kab. Parigi Moutong',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (403,'ID029','ID029007','Kab. Poso',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (404,'ID029','ID029008','Kab. Sigi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (405,'ID029','ID029009','Kab. Tojo Una-Una',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (406,'ID029','ID029010','Kab. Toli-Toli',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (407,'ID029','ID029011','Kota Palu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (408,'ID030','ID030001','Kab. Bombana',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (409,'ID030','ID030002','Kab. Buton',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (410,'ID030','ID030003','Kab. Buton Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (411,'ID030','ID030004','Kab. Kolaka',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (412,'ID030','ID030005','Kab. Kolaka Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (413,'ID030','ID030006','Kab. Konawe',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (414,'ID030','ID030007','Kab. Konawe Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (415,'ID030','ID030008','Kab. Konawe Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (416,'ID030','ID030009','Kab. Muna',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (417,'ID030','ID030010','Kab. Wakatobi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (418,'ID030','ID030011','Kota Bau-Bau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (419,'ID030','ID030012','Kota Kendari',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (420,'ID031','ID031001','Kab. Bolaang Mongondow',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (421,'ID031','ID031002','Kab. Bolaang Mongondow Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (422,'ID031','ID031003','Kab. Bolaang Mongondow Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (423,'ID031','ID031004','Kab. Bolaang Mongondow Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (424,'ID031','ID031005','Kab. Kepulauan Sangihe',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (425,'ID031','ID031006','Kab. Kepulauan Siau Tagulandang Biaro',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (426,'ID031','ID031007','Kab. Kepulauan Talaud',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (427,'ID031','ID031008','Kab. Minahasa',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (428,'ID031','ID031009','Kab. Minahasa Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (429,'ID031','ID031010','Kab. Minahasa Tenggara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (430,'ID031','ID031011','Kab. Minahasa Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (431,'ID031','ID031012','Kota Bitung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (432,'ID031','ID031013','Kota Kotamobagu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (433,'ID031','ID031014','Kota Manado',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (434,'ID031','ID031015','Kota Tomohon',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (435,'ID032','ID032001','Kab. Agam',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (436,'ID032','ID032002','Kab. Dharmasraya',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (437,'ID032','ID032003','Kab. Kepulauan Mentawai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (438,'ID032','ID032004','Kab. Lima Puluh Koto/Kota',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (439,'ID032','ID032005','Kab. Padang Pariaman',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (440,'ID032','ID032006','Kab. Pasaman',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (441,'ID032','ID032007','Kab. Pasaman Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (442,'ID032','ID032008','Kab. Pesisir Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (443,'ID032','ID032009','Kab. Sijunjung',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (444,'ID032','ID032010','Kab. Solok',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (445,'ID032','ID032011','Kab. Solok Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (446,'ID032','ID032012','Kab. Tanah Datar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (447,'ID032','ID032013','Kota Bukittinggi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (448,'ID032','ID032014','Kota Padang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (449,'ID032','ID032015','Kota Padang Panjang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (450,'ID032','ID032016','Kota Pariaman',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (451,'ID032','ID032017','Kota Payakumbuh',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (452,'ID032','ID032018','Kota Sawah Lunto',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (453,'ID032','ID032019','Kota Solok',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (454,'ID033','ID033001','Kab. Banyuasin',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (455,'ID033','ID033002','Kab. Empat Lawang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (456,'ID033','ID033003','Kab. Lahat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (457,'ID033','ID033004','Kab. Muara Enim',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (458,'ID033','ID033005','Kab. Musi Banyuasin',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (459,'ID033','ID033006','Kab. Musi Rawas',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (460,'ID033','ID033007','Kab. Ogan Ilir',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (461,'ID033','ID033008','Kab. Ogan Komering Ilir',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (462,'ID033','ID033009','Kab. Ogan Komering Ulu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (463,'ID033','ID033010','Kab. Ogan Komering Ulu Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (464,'ID033','ID033011','Kab. Ogan Komering Ulu Timur',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (465,'ID033','ID033012','Kota Lubuk Linggau',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (466,'ID033','ID033013','Kota Pagar Alam',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (467,'ID033','ID033014','Kota Palembang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (468,'ID033','ID033015','Kota Prabumulih',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (469,'ID034','ID034001','Kab. Asahan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (470,'ID034','ID034002','Kab. Batu Bara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (471,'ID034','ID034003','Kab. Dairi',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (472,'ID034','ID034004','Kab. Deli Serdang',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (473,'ID034','ID034005','Kab. Humbang Hasundutan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (474,'ID034','ID034006','Kab. Karo',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (475,'ID034','ID034007','Kab. Labuhan Batu',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (476,'ID034','ID034008','Kab. Labuhan Batu Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (477,'ID034','ID034009','Kab. Labuhan Batu Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (478,'ID034','ID034010','Kab. Langkat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (479,'ID034','ID034011','Kab. Mandailing Natal',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (480,'ID034','ID034012','Kab. Nias',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (481,'ID034','ID034013','Kab. Nias Barat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (482,'ID034','ID034014','Kab. Nias Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (483,'ID034','ID034015','Kab. Nias Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (484,'ID034','ID034016','Kab. Padang Lawas',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (485,'ID034','ID034017','Kab. Padang Lawas Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (486,'ID034','ID034018','Kab. Pakpak Bharat',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (487,'ID034','ID034019','Kab. Samosir',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (488,'ID034','ID034020','Kab. Serdang Bedagai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (489,'ID034','ID034021','Kab. Simalungun',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (490,'ID034','ID034022','Kab. Tapanuli Selatan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (491,'ID034','ID034023','Kab. Tapanuli Tengah',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (492,'ID034','ID034024','Kab. Tapanuli Utara',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (493,'ID034','ID034025','Kab. Toba Samosir',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (494,'ID034','ID034026','Kota Binjai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (495,'ID034','ID034027','Kota Gunungsitoli',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (496,'ID034','ID034028','Kota Medan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (497,'ID034','ID034029','Kota Padang Sidempuan',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (498,'ID034','ID034030','Kota Pematang Siantar',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (499,'ID034','ID034031','Kota Sibolga',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (500,'ID034','ID034032','Kota Tanjung Balai',1);
insert  into `bg_ks_directory_regency`(`id`,`province_code`,`regency_code`,`regency_name`,`active`) values (501,'ID034','ID034033','Kota Tebing Tinggi',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
