<div class="notfound_block">
	<h1><?php echo $this->__('Page Not Found'); ?></h1>
	<div class="info1"><?php echo $this->__('The page you requested was not found.'); ?></div>
	<div class="info2"><?php echo $this->__('Please make sure your URL & spelling is correct.'); ?></div>
	<div class="separator"></div>
	<div class="info3"><?php echo $this->__('Please follow this button to get back on the track.'); ?></div>
	<div class="buttons"><a class="backhome" href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('Go To Homepage'); ?></a></div>
</div>