<?php
/**
 * Magento
 *
 * @author    Faspay http://faspay.mediaindonusa.com <cs@mediaindonusa.com>
 * @copyright Copyright (C) 2013 MediaIndonusa. (http://faspay.mediaindonusa.com)
 *
**/

?>
<?php
	echo $this->getMethod()->getTitle() . '<br/>';
	if ($this->getInfo()->getLastTransId() == '') {
		//echo $this->__('Payment has not been processed yet.') . '<br/>';
	} else {
		echo $this->__('Faspay Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
	}
?>