<section id="highlight-block" class="container hidden-sm hidden-xs">
    <div class="row">
        <!-- highlight item  -->
        <?php echo $this->getChildHtml('highlightlist') ?>
        <!-- most view item -->
        <div class="col-md-3">
            <?php $collection = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()->getData(); ?>
            <?php //print_r(count($collection)); ?>
            <?php if(count($collection) > 0) : ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->__('Recently Viewed Items'); ?></h3>
                </div>
                <div class="panel-body">
                    <?php echo $this->getChildHtml('productviewed') ?>
                </div>
            </div>
            <?php else : ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->__('Most Popular Items'); ?></h3>
                </div>
                <div class="panel-body">
                    <?php echo $this->getChildHtml('mosthits') ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</section>